apiVersion: v1
kind: Pod
metadata:
  # Unique key of the Job instance
  generateName: run-seeds-app-
spec:
  containers:
  - name: db-migration
    image: eu.gcr.io/sense-219918/sense_app:latest
    resources:
      requests:
        cpu: "10m"
    command: ["mix"]
    args: ["do", "ecto.seeds"]
    env:
      - name: MIX_ENV
        value: prod
      - name: INFLUXDB_HOST
        value: influxdb
      - name: PG_HOST
        value: postgres
      - name: PG_USERNAME
        value: postgres
  restartPolicy: Never
